apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-headless-svc"
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
  - name: {{ .Values.service.port.name }}
    port: {{ .Values.service.port.port }}
    targetPort: {{ .Values.service.port.targetPort }}
    protocol: {{ .Values.service.port.protocol }}
  selector:
    app: {{ .Chart.Name }}