
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Chart.Name }}-secrets"
data:
  username: {{ .Values.secret.username | b64enc }}
  password: {{ .Values.secret.password | b64enc }}
  database: {{ .Values.secret.database | b64enc }}