apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Chart.Name }}-sts"
spec:
  serviceName: "{{ .Chart.Name }}-headless-svc"
  replicas: {{ .Values.statefulSet.replicas}}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Values.service.port.name }}
          image: "{{ .Values.statefulSet.image.name }}:{{ .Values.statefulSet.image.tag }}"
          imagePullPolicy: {{ .Values.statefulSet.imagePullPolicy | quote}}
          env:
            - name: PGDATA
              value: {{ .Values.statefulSet.env.values.PGDATA | quote }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: "{{ .Chart.Name }}-secrets"
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Chart.Name }}-secrets"
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: "{{ .Chart.Name }}-secrets"
                  key: database
          ports:
            - name: {{ .Values.service.port.name }}
              containerPort: {{ .Values.service.port.port }}
              protocol: {{ .Values.service.port.protocol }}
          volumeMounts:
            - name: {{ .Values.statefulSet.pvc.name }}
              mountPath: {{ .Values.statefulSet.pvc.mountPath }}
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
                - -d
                - FilmMatch11
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
                - -d
                - FilmMatch11
            initialDelaySeconds: 30
            periodSeconds: 30
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.statefulSet.pvc.name }}
      spec:
        accessModes:
          - {{ .Values.statefulSet.pvc.accessMode | quote }}
        resources:
          requests:
            storage: {{ .Values.statefulSet.pvc.storage | quote }}