namespace: test1
enabled: true

ingressClassName: nginx

frontend:
  host: film.local
  serviceName: frontend
  servicePort: 80

backend:
  host: api.film.local
  serviceName: backend-service
  servicePort: 80
