apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: bahlish/film-match-front:1
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: "http://api.film.local" 
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
