apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
  namespace: back
  labels:
    app: back-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: back-pod
  template:
    metadata:
      labels:
        app: back-pod
    spec:
      containers:
      - name: back-pod
        image: bahlish/film-match:1.3
        ports:
        - containerPort: 8080
        env:
          - name: ConnectionStrings__DefaultConnection
            valueFrom:
              secretKeyRef:
                name: back-secrets
                key: connection-string
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
